# Generated by Django 5.0.3 on 2024-04-11 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordings',
            name='patient',
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='patient', max_length=100)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.IntegerField(default='0')),
                ('age', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('hyper_tension_bp', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('palpitation', models.BooleanField(default=False)),
                ('surgery', models.BooleanField(default=False)),
                ('other', models.TextField(default='', max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient_details',
        ),
        migrations.DeleteModel(
            name='recordings',
        ),
    ]
