# Generated by Django 5.0.3 on 2024-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='forecast',
            field=models.TextField(blank=True),
        ),
    ]
