# Generated by Django 5.0.3 on 2024-04-11 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0002_delete_health_doctor_profile_forecast'),
        ('patient_details', '0002_remove_recordings_patient_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='DOCTOR', max_length=50)),
                ('license_no', models.CharField(default='XXXXX', max_length=50)),
                ('specialty', models.CharField(default='XXXXX', max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phone_number', models.CharField(default=0, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_beat', models.IntegerField()),
                ('forecast', models.CharField(choices=[('H', 'Healthy'), ('U', 'Un-Healthy')], max_length=1)),
                ('graph', models.ImageField(upload_to='graph/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_details.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_details.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor_profile',
        ),
    ]
